### ISSUE TITLE
您好，感谢您的回复

### ISSUE THREAD

**Issue by abcdetab** [Basicname/RKNN-FaceRecognition#2]
我在网上找到了一个112*112输入输出是512的特征向量，但是它的结构好像有点问题，我有个问题，我在量化的时候设置的参数是000和255，255，255那我在送进npu计算的时候还需要将图像数据归一化转成浮点数吗。我自己也转化了一个，但是精度特别低，我可以跟您请教一下吗

**Comment by Basicname** [comment]
我记得rk官方的手册里说，转模型的时候如果添加了量化参数，再进行推理的时候就不用转成浮点数了，我测试的时候也没有量化mobilefacenet，但是retinanet应该是量化了，记得不是很清
